// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token   string  `json:"token"`
	Message *string `json:"message,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
